






# -*- coding: utf-8 -*-

# Macro Begin: /home/henrique/snap/freecad/common/part.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD
import Part
import PartDesignGui

P101_Lado_1_Z = 50.00
P102_Lado_1_X = 100.00
P103_Lado_1_Y = 100.00

App.newDocument()
#App.activeDocument().addObject( 'PartDesign::CoordinateSystem', 'Lado_1' )
#App.ActiveDocument.ActiveObject.Placement = App.Placement(App.Vector(0.00,0.00,P101_Lado_1_Z),App.Rotation(App.Vector(0.00,0.00,1.00),0.00))

pastaPlanilhas = App.activeDocument().addObject('App::DocumentObjectGroup','Planilhas')

planilhaDadosBloco = App.activeDocument().addObject('Spreadsheet::Sheet','Dados_bloco')
planilhaDadosBloco.Label = "Dados do bloco"
planilhaDadosBloco.setDisplayUnit('B1:B3', 'mm')
texto = 'P101_Lado_1_Z'
planilhaDadosBloco.set('A1',texto)
planilhaDadosBloco.setAlias('B1',texto)
texto = 'P102_Lado_1_X'
planilhaDadosBloco.set('A1',texto)
planilhaDadosBloco.setAlias('B1',texto)
texto = 'P103_Lado_1_Y'
planilhaDadosBloco.set('A1',texto)
planilhaDadosBloco.setAlias('B1',texto)
planilhaDadosBloco.recompute()
pastaPlanilhas.addObject(planilhaDadosBloco)

planilhaSubProgramas = App.activeDocument().addObject('Spreadsheet::Sheet','Sub_programas')
pastaPlanilhas.addObject(planilhaSubProgramas)
planilhaSubProgramas.setColumnWidth('A',50)
planilhaSubProgramas.setColumnWidth('B',300)
planilhaSubProgramas.set('B1','INICIO DO BLOCO HIDRÁULICO')
planilhaSubProgramas.set('B2','TROCA DE FERRAMENTA')
planilhaSubProgramas.set('B3','APROXIMAR DO FURO')
planilhaSubProgramas.set('B4','LIGAR REFRIGERAÇÃO')
planilhaSubProgramas.set('B5','SAIR DO FURO')
planilhaSubProgramas.set('B6','DESLIGAR REFRIGERAÇÃO')
planilhaSubProgramas.set('A7','SUB 1')
planilhaSubProgramas.set('B7','VERIFICAR K NA TABELA DE FERRAMENTAS')
planilhaSubProgramas.set('A8','SUB 2')
planilhaSubProgramas.set('B8','TROCAR LADO BLOCO HIDRAULICO')
planilhaSubProgramas.set('A9','SUB 3')
planilhaSubProgramas.set('B9','PICA-PAU SEM RETORNO')
planilhaSubProgramas.set('A10','SUB 4')
planilhaSubProgramas.set('B10','PICA-PAU COM RETORNO A Z2')
planilhaSubProgramas.set('B11','FIM DO BLOCO HIDRÁULICO')
planilhaSubProgramas.recompute()

planilhaProgramaCNC = App.activeDocument().addObject('Spreadsheet::Sheet','Programa_CNC')
planilhaProgramaCNC.Label = "Programa CNC"
pastaPlanilhas.addObject(planilhaProgramaCNC)
planilhaProgramaCNC.setColumnWidth('A',50)
planilhaProgramaCNC.setColumnWidth('B',30)
planilhaProgramaCNC.setColumnWidth('C',30)
planilhaProgramaCNC.setColumnWidth('D',30)
planilhaProgramaCNC.setColumnWidth('E',200)
planilhaProgramaCNC.setColumnWidth('F',30)
planilhaProgramaCNC.setColumnWidth('G',60)
planilhaProgramaCNC.setColumnWidth('H',30)
planilhaProgramaCNC.setColumnWidth('I',40)
planilhaProgramaCNC.setAlignment('A1:N100', 'center', 'keep')
planilhaProgramaCNC.setAlignment('A1:N100', 'vcenter', 'keep')
planilhaProgramaCNC.setBackground('A2:N2', (0.752941,0.752941,0.752941,1.000000))
planilhaProgramaCNC.setAlignment('A3:A30', 'right', 'keep')
planilhaProgramaCNC.setAlignment('C3:C30', 'right', 'keep')
planilhaProgramaCNC.setAlignment('D3:D30', 'left', 'keep')
planilhaProgramaCNC.mergeCells('A2:B2')
planilhaProgramaCNC.mergeCells('C2:D2')
planilhaProgramaCNC.set('A2:A30','Lado')
planilhaProgramaCNC.set('C3:C30','- T')
planilhaProgramaCNC.set('F3:F30','S')
planilhaProgramaCNC.set('H3:H30','F')
planilhaProgramaCNC.set('C2','T')
planilhaProgramaCNC.set('E2','Descrição Ferramenta')
planilhaProgramaCNC.set('G2','S')
planilhaProgramaCNC.set('I2','F')
planilhaProgramaCNC.recompute()

Gui.activateWorkbench("PartWorkbench")
App.activeDocument().Label = "Bloco hidráulico"
objectName = "Bloco_Faceado"
App.ActiveDocument.addObject("Part::Box",objectName)
App.ActiveDocument.getObject(objectName).Label = "Bloco Maciço"
App.ActiveDocument.getObject(objectName).Length = P102_Lado_1_X
App.ActiveDocument.getObject(objectName).Width = P103_Lado_1_Y
App.ActiveDocument.getObject(objectName).Height = P101_Lado_1_Z
App.ActiveDocument.recompute()

objectName = "Furo"
App.ActiveDocument.addObject("Part::Cylinder",objectName)
App.ActiveDocument.ActiveObject.Label = "Furo de pressão"
App.ActiveDocument.getObject(objectName).Radius = '4.00 mm'
App.ActiveDocument.getObject(objectName).Placement = App.Placement(App.Vector(9.00,9.00,40.00),App.Rotation(App.Vector(0.00,0.00,1.00),0.00))
FreeCADGui.ActiveDocument.ActiveObject.ShapeColor = (1.00,0.00,0.00)

App.activeDocument().addObject("Part::Cut","Bloco_Hidraulico")
App.activeDocument().Bloco_Hidraulico.Base = App.activeDocument().Bloco_Faceado
App.activeDocument().Bloco_Hidraulico.Tool = App.activeDocument().Furo
FreeCADGui.ActiveDocument.ActiveObject.Transparency = 90
App.ActiveDocument.recompute()
Gui.activeDocument().activeView().viewDefaultOrientation('Trimetric',0)
Gui.SendMsgToActiveView("ViewFit")