# -*- coding: utf-8 -*-

# Macro Begin: /home/henrique/snap/freecad/common/part.FCMacro +++++++++++++++++++++++++++++++++++++++++++++++++
import FreeCAD
import Part
import PartDesignGui

planilhaProgramaCNC = App.activeDocument().getObject('Programa_CNC')

print("lendo..")
P101_Lado_1_Z = planilhaProgramaCNC.get('Z_P101')
P102_Lado_1_X = planilhaProgramaCNC.get('X_P102')
P103_Lado_1_Y = planilhaProgramaCNC.get('Y_P103')

print(P101_Lado_1_Z)
print(P102_Lado_1_X)
print(P103_Lado_1_Y)

Gui.activateWorkbench("PartWorkbench")
'''
App.activeDocument().Label = "Bloco hidráulico"
objectName = "Bloco_Faceado"
App.ActiveDocument.addObject("Part::Box",objectName)
App.ActiveDocument.getObject(objectName).Label = "Bloco Maciço"
App.ActiveDocument.getObject(objectName).Length = P102_Lado_1_X
App.ActiveDocument.getObject(objectName).Width = P103_Lado_1_Y
App.ActiveDocument.getObject(objectName).Height = P101_Lado_1_Z
App.ActiveDocument.getObject(objectName).Placement = App.Placement(App.Vector(0.00,-P103_Lado_1_Y,0.00),App.Rotation(App.Vector(0.00,0.00,1.00),0.00))
App.ActiveDocument.recompute()

'''
x = 6
X = planilhaProgramaCNC.get('K'+str(x))
print(X)
Y = planilhaProgramaCNC.get('M'+str(x))
print(Y)
Zi = planilhaProgramaCNC.get('O'+str(x))
print(Zi)
Zf = planilhaProgramaCNC.get('Q'+str(x))
print(Zf)

def modelarFuro(numFuro, lado, diam, X, Y, Zi, Zf):
    objectName = "Furo" + str(numFuro)
    print(objectName)
    print("Lado = " + str(lado))
    print("X = " + str(X))
    print("Y = " + str(Y))
    print("Zi = " + str(Zi))
    print("Zf = " + str(Zf))
    App.ActiveDocument.addObject("Part::Cylinder",objectName)
    App.ActiveDocument.ActiveObject.Label = "Furo Ø" + str(diam)
    App.ActiveDocument.getObject(objectName).Radius = diam/2
    App.ActiveDocument.getObject(objectName).Height = Zi - Zf
    X_Furo = X
    Y_Furo = Y
    Z_Furo = P101_Lado_1_Z + Zf
    App.ActiveDocument.getObject(objectName).Placement = App.Placement(App.Vector(X_Furo,Y_Furo,Z_Furo),App.Rotation(App.Vector(0.00,0.00,1.00),0.00))
    FreeCADGui.ActiveDocument.ActiveObject.ShapeColor = (1.00,0.00,0.00)
    App.ActiveDocument.recompute()
modelarFuro(1, 3, 8.0, 25,-67, Zi, Zf)
modelarFuro(2, 3, 5.0, 55,-67, Zi, Zf)
modelarFuro(3, 3, 5.0, 55,-17, Zi, Zf)
'''

App.activeDocument().addObject("Part::Cut","Bloco_Hidraulico")
App.activeDocument().Bloco_Hidraulico.Base = App.activeDocument().Bloco_Faceado
App.activeDocument().Bloco_Hidraulico.Tool = App.activeDocument().Furo
FreeCADGui.ActiveDocument.ActiveObject.Transparency = 90
App.ActiveDocument.recompute()
Gui.activeDocument().activeView().viewDefaultOrientation('Trimetric',0)
Gui.SendMsgToActiveView("ViewFit")

App.ActiveDocument.getObject('Programa_CNC').ViewObject.doubleClicked()'''