print("----------Inicio--------------")
#App.activeDocument().addObject("Part::MultiFuse","Fusion")
#App.activeDocument().Fusion.Shapes = Gui.Selection.addSelection(App.ActiveDocument.getObject("Furos").Group
#lista = []

#x=0
#for i in App.ActiveDocument.getObject("Furos").Group:
    #App.activeDocument().Fusion.Shapes += Gui.Selection.addSelection(App.ActiveDocument.getObject("Furos").Group[x])
    #nome = App.ActiveDocument.getObject("Furos").Group[x].Name
    #App.activeDocument().Fusion.Shapes += App.ActiveDocument.getObject(nome)
    #lista += App.ActiveDocument.getObject(nome)
    #Gui.Selection.addSelection(App.ActiveDocument.getObject(nome))
    #Gui.Selection.addSelection(App.ActiveDocument.getObject("Furos").Group[x])
    #x=x+1
#print("----------Fim--------------")
#App.activeDocument().addObject("Part::MultiFuse","Fusion")
#App.activeDocument().Fusion.Shapes = [App.activeDocument().Furo7,App.activeDocument().Cone7,App.activeDocument().Furo14,App.activeDocument().Cone14,App.activeDocument().Furo21,App.activeDocument().Cone21,App.activeDocument().Furo28,App.activeDocument().Cone28,App.activeDocument().Furo29,App.activeDocument().Cone29,App.activeDocument().Furo34,App.activeDocument().Cone34,App.activeDocument().Furo35,App.activeDocument().Cone35,App.activeDocument().Furo40,App.activeDocument().Cone40,App.activeDocument().Furo41,App.activeDocument().Cone41,App.activeDocument().Furo46,App.activeDocument().Cone46,App.activeDocument().Furo47,App.activeDocument().Cone47,App.activeDocument().Furo54,App.activeDocument().Cone54,App.activeDocument().Furo55,App.activeDocument().Cone55,App.activeDocument().Furo60,App.activeDocument().Cone60,App.activeDocument().Furo61,App.activeDocument().Cone61,App.activeDocument().Furo66,App.activeDocument().Cone66,App.activeDocument().Furo67,App.activeDocument().Cone67,App.activeDocument().Furo72,App.activeDocument().Cone72,App.activeDocument().Furo73,App.activeDocument().Cone73,]
#print(lista)
#Gui.runCommand('Part_Fuse',0)
'''
from FreeCAD import Base
d1_min = 10.0
d2_max = 20.0
h_max = 2.0
Pnt0 = Base.Vector(d1_min / 2.0, 0.0, h_max)
Pnt2 = Base.Vector(d2_max / 2.0, 0.0, h_max)
Pnt3 = Base.Vector(d2_max / 2.0, 0.0, 0.0)
Pnt4 = Base.Vector(d1_min / 2.0, 0.0, 0.0)
Pnt1 = Base.Vector(d2_max / 2.0 - h_max / 4.0, 0.0, h_max)
Pnt2 = Base.Vector(d2_max / 2.0, 0.0, h_max * 0.75)
edge1 = Part.makeLine(Pnt0, Pnt1)
edgeCham = Part.makeLine(Pnt1, Pnt2)
edge1 = Part.Wire([edge1, edgeCham])
edge2 = Part.makeLine(Pnt2, Pnt3)
edge3 = Part.makeLine(Pnt3, Pnt4)
edge4 = Part.makeLine(Pnt4, Pnt0)
aWire = Part.Wire([edge1, edge2, edge3, edge4])
Part.show(aWire)
aFace = Part.Face(aWire)
letra = aFace.extrude(App.Vector(0, 0, 10))
Part.show(letra)
'''
import Draft
def modelarNumeroLados(P101_Lado_1_Z, P102_Lado_1_X, P103_Lado_1_Y, tamanho, espessura):
    fonte="/usr/share/fonts/TTF/DejaVuSans.ttf"
    
    numLado="1"
    texto=Draft.make_shapestring(String=numLado, FontFile=fonte, Size=tamanho, Tracking=0.0)
    texto.Placement=FreeCAD.Placement(App.Vector(P102_Lado_1_X-tamanho,-P103_Lado_1_Y+tamanho+1.0,0.00),App.Rotation(App.Vector(1.00,0.00,0.00),180.00))
    FreeCAD.ActiveDocument.addObject('Part::Extrusion','Lado_'+numLado)
    f = FreeCAD.ActiveDocument.getObject('Lado_'+numLado)
    f.Base = FreeCAD.ActiveDocument.getObject('ShapeString')
    f.LengthFwd = espessura
    FreeCADGui.ActiveDocument.getObject('Lado_'+numLado).ShapeColor = (0.00,0.00,0.00)
    
    numLado="2"
    texto=Draft.make_shapestring(String=numLado, FontFile=fonte, Size=tamanho, Tracking=0.0)
    texto.Placement=FreeCAD.Placement(App.Vector(P102_Lado_1_X-tamanho,-espessura,tamanho+1.00),App.Rotation(App.Vector(1.00,0.00,0.00),270.00))
    FreeCAD.ActiveDocument.addObject('Part::Extrusion','Lado_'+numLado)
    f = FreeCAD.ActiveDocument.getObject('Lado_'+numLado)
    f.Base = FreeCAD.ActiveDocument.getObject('ShapeString001')
    f.Dir = (0.00, 1.00, 0.00)
    f.LengthFwd = espessura
    FreeCADGui.ActiveDocument.getObject('Lado_'+numLado).ShapeColor = (0.00,0.00,0.00)
    
    numLado="3"
    texto=Draft.make_shapestring(String=numLado, FontFile=fonte, Size=tamanho, Tracking=0.0)
    texto.Placement=FreeCAD.Placement(App.Vector(P102_Lado_1_X-tamanho, -tamanho-1.0, P101_Lado_1_Z-espessura),App.Rotation(App.Vector(0.00,0.00,1.00),0.00))
    FreeCAD.ActiveDocument.addObject('Part::Extrusion','Lado_'+numLado)
    f = FreeCAD.ActiveDocument.getObject('Lado_'+numLado)
    f.Base = FreeCAD.ActiveDocument.getObject('ShapeString002')
    f.LengthFwd = espessura
    FreeCADGui.ActiveDocument.getObject('Lado_'+numLado).ShapeColor = (0.00,0.00,0.00)
    
    numLado="4"
    texto=Draft.make_shapestring(String=numLado, FontFile=fonte, Size=tamanho, Tracking=0.0)
    texto.Placement=FreeCAD.Placement(App.Vector(P102_Lado_1_X-tamanho,-P103_Lado_1_Y,P101_Lado_1_Z-tamanho-1.0),App.Rotation(App.Vector(1.00,0.00,0.00),90.00))
    FreeCAD.ActiveDocument.addObject('Part::Extrusion','Lado_'+numLado)
    f = FreeCAD.ActiveDocument.getObject('Lado_'+numLado)
    f.Base = FreeCAD.ActiveDocument.getObject('ShapeString003')
    f.Dir = (0.00, 1.00, 0.00)
    f.LengthFwd = espessura
    FreeCADGui.ActiveDocument.getObject('Lado_'+numLado).ShapeColor = (0.00,0.00,0.00)
    
    numLado="5"
    texto=Draft.make_shapestring(String=numLado, FontFile=fonte, Size=tamanho, Tracking=0.0)
    texto.Placement=FreeCAD.Placement(App.Vector(0.00, -tamanho, tamanho+1.0),App.Rotation(App.Vector(0.58,0.58,-0.58),240.00))
    FreeCAD.ActiveDocument.addObject('Part::Extrusion','Lado_'+numLado)
    f = FreeCAD.ActiveDocument.getObject('Lado_'+numLado)
    f.Base = FreeCAD.ActiveDocument.getObject('ShapeString004')
    f.Dir = (1.00, 0.00, 0.00)
    f.LengthFwd = espessura
    FreeCADGui.ActiveDocument.getObject('Lado_'+numLado).ShapeColor = (0.00,0.00,0.00)
    
    numLado="6"
    texto=Draft.make_shapestring(String=numLado, FontFile=fonte, Size=tamanho, Tracking=0.0)
    texto.Placement=FreeCAD.Placement(App.Vector(P102_Lado_1_X-espessura,-tamanho-1.0,P101_Lado_1_Z-tamanho-1.0),App.Rotation(App.Vector(0.58,0.58,0.58),120.00))
    FreeCAD.ActiveDocument.addObject('Part::Extrusion','Lado_'+numLado)
    f = FreeCAD.ActiveDocument.getObject('Lado_'+numLado)
    f.Base = FreeCAD.ActiveDocument.getObject('ShapeString005')
    f.Dir = (1.00, 0.00, 0.00)
    f.LengthFwd = espessura
    FreeCADGui.ActiveDocument.getObject('Lado_'+numLado).ShapeColor = (0.00,0.00,0.00)
    
    App.activeDocument().addObject("Part::MultiFuse","Numeros")
    App.activeDocument().Numeros.Shapes = [App.activeDocument().Lado_1,App.activeDocument().Lado_2,App.activeDocument().Lado_3,App.activeDocument().Lado_4,App.activeDocument().Lado_5,App.activeDocument().Lado_6,]
    Gui.activeDocument().Lado_1.Visibility=False
    Gui.activeDocument().Lado_2.Visibility=False
    Gui.activeDocument().Lado_3.Visibility=False
    Gui.activeDocument().Lado_4.Visibility=False
    Gui.activeDocument().Lado_5.Visibility=False
    Gui.activeDocument().Lado_6.Visibility=False
    
    App.activeDocument().addObject("Part::Cut","Bloco_numerado")
    App.activeDocument().Bloco_numerado.Base = App.activeDocument().Bloco_Faceado
    App.activeDocument().Bloco_numerado.Tool = App.activeDocument().Numeros
    App.activeDocument().recompute()
modelarNumeroLados(44.0, 52.0, 71.0, 3.0, 1.0)
print("----------Fim--------------")
